-- =====================================================================
-- Technology Sales · base vacía para Supabase STAGING
-- Ejecutar únicamente en el proyecto de pruebas.
-- Después ejecutar, en orden:
--   1. supabase_schema.sql
--   2. supabase_security_hardening.sql
--   3. supabase_staging_seed.sql
-- =====================================================================

begin;

create extension if not exists pgcrypto;

create table if not exists public.inventario (
  id bigint generated by default as identity primary key,
  categoria text,
  marca text,
  modelo text not null,
  capacidad text,
  color text,
  chip text,
  sucursal text,
  cantidad integer not null default 0,
  consignacion integer not null default 0,
  comprometido integer not null default 0,
  estado text,
  imagen text,
  individual boolean not null default false,
  imei text,
  bateria integer,
  ciclos integer,
  garantia text,
  vence text,
  created_at timestamptz not null default now()
);

create index if not exists inventario_catalogo_idx
  on public.inventario (marca, modelo, capacidad, chip, estado);

create index if not exists inventario_sucursal_idx
  on public.inventario (sucursal);

create table if not exists public.precios (
  id bigint generated by default as identity primary key,
  marca text,
  modelo text not null,
  capacidad text,
  chip text,
  estado text,
  precio_mayorista numeric,
  precio_reventa numeric,
  precio_publico numeric,
  created_at timestamptz not null default now()
);

create unique index if not exists precios_variante_uidx
  on public.precios (
    upper(trim(coalesce(marca, ''))),
    upper(trim(coalesce(modelo, ''))),
    upper(trim(coalesce(capacidad, ''))),
    upper(trim(coalesce(chip, ''))),
    upper(trim(coalesce(estado, '')))
  );

commit;

